[project]
name = "abb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "specify-cli",
]

[tool.uv.sources]
specify-cli = { git = "https://github.com/github/spec-kit.git" }
