name: 🌐 Azure Static Web Apps (Staging)

# Optimized for Staging Deployment - Quality Checks delegated to Qodo
# This workflow now depends on streamlined-ci for essential checks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  NODE_VERSION: '20'

jobs:
  # ⚡ Dependency auf streamlined CI für essential checks
  wait-for-essential-checks:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: 🔗 Wait for Essential CI Checks
    steps:
      - name: 📋 Check Status
        run: |
          echo "✅ Essential CI checks (streamlined-ci.yml) must pass before deployment"
          echo "🤖 Style/Quality checks handled by Qodo"
          echo "🚀 Ready for Azure deployment after essential checks pass"

  build_and_deploy:
    needs: wait-for-essential-checks
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web Apps
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Azure deployment with integrated build and test pipeline
      - name: Deploy to Azure Static Web Apps (with Unit Tests)
        id: builddeploy
        if: vars.AZURE_DEPLOYMENT_ENABLED == 'true'
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: ".output/server"
          output_location: ".output/public"
          # Let Azure handle the build and test pipeline in Free Tier
          skip_app_build: false
          # Azure build configuration for Free Tier
          app_build_command: |
            npm ci --prefer-offline --no-audit &&
            npm run test -- --reporter=dot --run &&
            npm run build
          api_build_command: "npm run build"

      - name: Prisma migrate deploy (Production)
        if: github.ref == 'refs/heads/main' && vars.AZURE_DEPLOYMENT_ENABLED == 'true'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PRISMA_SCHEMA: prisma/schema.prod.prisma
        run: |
          if [ ! -f "$PRISMA_SCHEMA" ]; then
            echo "WARN: $PRISMA_SCHEMA not found. Falling back to default schema.prisma";
            export PRISMA_SCHEMA=prisma/schema.prisma;
          fi
          npx prisma migrate deploy

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && vars.AZURE_DEPLOYMENT_ENABLED == 'true'
    runs-on: ubuntu-latest
    name: Close Azure SWA PR Environment
    steps:
      - name: Close PR Environment
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
          app_location: "/"  # Required parameter
