name: Qodo - Apply Suggestions

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: read

jobs:
  apply:
    if: ${{ github.event.issue.pull_request != null && contains(github.event.comment.body, '/qodo-apply') }}
    runs-on: ubuntu-latest
    steps:
      - name: Fetch PR info
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          resp=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.issue.number }}")
          head_ref=$(echo "$resp" | jq -r '.head.ref')
          head_repo=$(echo "$resp" | jq -r '.head.repo.full_name')
          base_repo=$(echo "$resp" | jq -r '.base.repo.full_name')
          echo "head_ref=$head_ref" >> $GITHUB_OUTPUT
          echo "head_repo=$head_repo" >> $GITHUB_OUTPUT
          echo "base_repo=$base_repo" >> $GITHUB_OUTPUT

      - name: "Guard: only apply for branches in same repository"
        if: ${{ steps.pr.outputs.head_repo != steps.pr.outputs.base_repo }}
        run: |
          echo "Head repo differs from base repo. Skipping for security."
          exit 0

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ steps.pr.outputs.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Apply Qodo/GitHub suggestions
        run: npm run apply:qodo -- --pr ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git commit -m "ci(qodo): apply suggestions from PR #${{ github.event.issue.number }}"
            git push
          else
            echo "No changes to commit."
          fi
